name: Content Fly Cloud Prod CI / CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'npm'
      - name: Install Firebase
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: |
          cd functions
          npm ci
      - name: Run code check
        run: |
          cd functions
          npm run lint
      - name: Deploy Cloud Functions
        run: |
          firebase use contentflyprod --token ${{ secrets.FIREBASE_TOKEN }}
          firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
